require File.dirname(__FILE__) + '/test_helper.rb'

class TestScbiTestcode < Test::Unit::TestCase

  def setup
  end
  
  def test_coding
    s='gcagcccagccaagcactgtacaggaatcctgtgaagcagctccagctatgtgtgaagaagaggacagcactgccttggtgtgtgacaatggctctgggctctgtaaggccggctttgctggggacgatgctcccagggctgttttcccatccattgtgggacgtcccagacatcagggggtgatggtgggaatgggacaaaaagacagctacgtgggtgacgaagcacagagcaaaagaggaatcctgaccctgaagtacccgatagaacatggcatcatcaccaactgggacgacatggaaaagatctggcaccactctttctacaatgagcttcgtgttgcccctgaagagcatcccaccctgctcacggaggcacccctgaaccccaaggccaaccgggagaaaatgactcaaattatgtttgagactttcaatgtcccagccatgtatgtggctatccaggcggtgctgtctctctatgcctctggacgcacaactggcatcgtgctggactctggagatggtgtcacccacaatgtccccatctatgagggctatgccttgccccatgccatcatgcgtctggatctggctggccgagatctcactgactacctcatgaagatcctgactgagcgtggctattccttcgttactactgctgagcgtgagattgtccgggacatcaaggagaaactgtgttatgtagctctggactttgaaaatgagatggccactgccgcatggtcatcctcccttgagaagagttacgagttgcctgatgggcaagtgatcaccatcggaaatgaacgtttccgctgcccagagaccctgttccagccatccttcatcgggatggagtctgctggcatccatgaaaccacctacaacagcatcatgaagtgtgatattgacatcaggaaggacctctatgctaacaatgtcctatcagggggcaccactatgtaccctggcattgccgaccgaatgcagaaggagatcacggccctagcacccagcaccatgaagatcaagatcattgcccctccggagcgcaaatactctgtctggatcggtggctccatcctggcctctctgtccaccttccagcagatgtggatcagcaaacaggaatacgatgaagccgggccttccattgtccaccgcaaatgcttctaaaacactttcctgctcctctctgtctcatgcacacaactgtgaatgtcctgtggaattatgccttcagttcttttccaaatcattcctagccaaagctctgactcgttacctatgtgttttttaataaatctgaaataggctactggt'

    tc=Testcode.new(s)

    assert_equal(tc.testcode_value,1.236)
    assert_equal(tc.coding_conclusion,:coding)
    
    puts tc.testcode_value
    puts tc.coding_conclusion
    
    
  end
  
  def test_non_coding
    
    s='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc'

    tc=Testcode.new(s)

    assert_equal(tc.testcode_value,0.448)
    assert_equal(tc.coding_conclusion,:non_coding)
    
    puts tc.testcode_value
    puts tc.coding_conclusion
        
  end
  
  def test_unknown
     s='AAAAATATATATTATATATATATATTATACGCTCTCTCTCTCTCTCTCTCTCTCTTCTCTCTCTCTCCCCCCCCCCCCCCCCCCCCCCCTTTTTTTTTTTTTTTTTTTTTTTTTTAAAAAAAAAAAAAAAAAAAAAAAAAAAAACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCcccaccctgctcacggaggcacccctgaaccccaaggccaaccgggagaaaatgactcaaattatgtttgagactttcaatgtcccagccatgtatgtggctatccaggcggtgctgtctctctatgcctctggacgcacaactggcatcgtgctggactctggagatggtgtcacccacaatgtccccatctatgagggctatgccttgccccatgccatcatgcgtctggatctggctggccgagatctcactgactacctcatgaagatcctgactgagcgtggctattccttcgttactactgctgagcgtgagattgtccgggacatcaaggagaaactgtgttatgtagctctggactttgaaaatgagatggccactgccgcatggtcatcctcccttgagaagagttacgagttgcctgatgggcaagtgatcaccatcGACCGTTACACTTACGGTATCAGTATGACGTACTACGTACTACTCAGTACGTCAGTAGCTACGGTACGTACGTAGCTACGTACGTACGTAGCGTACGTATAGCGTACGTACATTC'

      tc=Testcode.new(s)

      assert_equal(tc.testcode_value,0.926)
      assert_equal(tc.coding_conclusion,:unknown)

      puts tc.testcode_value
      puts tc.coding_conclusion
    
    
  end
end
